name: caisse_dashboard
description: Dashboard de caisse Flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6

  # PDF & fichiers
  pdf: ^3.10.8
  path_provider: ^2.1.4
  open_document: ^1.0.7
  file_picker: ^10.3.8   # OK avec Flutter 3.38

  # Base de donnÃ©es
  drift: ^2.21.0
  drift_sqflite: ^2.0.1
  sqlite3_flutter_libs: ^0.5.27
  sqlite3: ^2.6.0
  sqflite: ^2.4.0
  path: ^1.9.0

  # Utilitaires
  to_csv: ^3.0.2
  encrypt: ^5.0.3
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  collection: ^1.18.0

  # Charts
  syncfusion_flutter_charts: ^32.1.23

  # Windows (STABLE Flutter 3.38)
  win32: 5.15.0   # ðŸ”’ pin exact pour Ã©viter les breaks natifs

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.21.0
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
